//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JL_gsbE5Entities : DbContext
    {
        public JL_gsbE5Entities()
            : base("name=JL_gsbE5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<activite_compl> activite_compl { get; set; }
        public DbSet<famille> famille { get; set; }
        public DbSet<inviter> inviter { get; set; }
        public DbSet<laboratoire> laboratoire { get; set; }
        public DbSet<medicament> medicament { get; set; }
        public DbSet<posseder> posseder { get; set; }
        public DbSet<praticien> praticien { get; set; }
        public DbSet<secteur> secteur { get; set; }
        public DbSet<specialite> specialite { get; set; }
        public DbSet<stats_prescriptions> stats_prescriptions { get; set; }
        public DbSet<type_praticien> type_praticien { get; set; }
        public DbSet<visiteur> visiteur { get; set; }
    }
}
